name: Feature request
description: Request an enhancement for neotest-ctest
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a new feature, please search [existing issues](https://github.com/orjangj/neotest-ctest/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement)
        to avoid creating duplicate feature requests.
  - type: textarea
    attributes:
      label: "Feature description"
      description: |
        A clear and concise description of what the feature is. May include images or other
        helpful resources to illustrate its functionality.
    validations:
      required: true
