name: Question
description: Ask a question about neotest-ctest
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Before asking, please search [existing issues](https://github.com/orjangj/neotest-ctest/issues?q=is%3Aopen+is%3Aissue+label%3Aquestion)
        or [discussions](https://github.com/orjangj/neotest-ctest/discussions) to avoid creating duplicate questions.
  - type: textarea
    attributes:
      label: "Question"
    validations:
      required: true
