local assert = require("luassert")
local adapter = require("neotest-ctest")
local config = require("neotest-ctest.config")

adapter.setup({})

describe("adapter.setup", function()
  it("should initialize default config", function()
    local expected_config = config.get_default()
    local actual_config = config.get()
    assert.are.same(expected_config, actual_config)
  end)
end)

describe("adapter.name", function()
  it("should equal neotest-ctest", function()
    assert.equals("neotest-ctest", adapter.name)
  end)
end)

describe("adapter.is_test_file", function ()
  it("should return true for default pattern", function()
    assert.is_true(adapter.is_test_file("/foo/bar_test.cc"))
    assert.is_true(adapter.is_test_file("/foo/bar_test.cpp"))
    assert.is_true(adapter.is_test_file("/foo/bar_test.cxx"))
  end)

  it("should return false for ordinary files", function()
    assert.is_false(adapter.is_test_file("/foo/example.cpp"))
    assert.is_false(adapter.is_test_file("/foo/CMakeLists.txt"))
    assert.is_false(adapter.is_test_file("/foo/no_extension"))
  end)
end)


describe("adapter.filter_dir", function ()
  it("should filter default directories", function()
    assert.is_false(adapter.filter_dir("build", "", ""))
    assert.is_false(adapter.filter_dir("cmake", "", ""))
    assert.is_false(adapter.filter_dir("doc", "", ""))
    assert.is_false(adapter.filter_dir("docs", "", ""))
    assert.is_false(adapter.filter_dir("examples", "", ""))
    assert.is_false(adapter.filter_dir("out", "", ""))
    assert.is_false(adapter.filter_dir("scripts", "", ""))
    assert.is_false(adapter.filter_dir("tools", "", ""))
    assert.is_false(adapter.filter_dir("venv", "", ""))
  end)

  it("should not filter other directories", function()
    assert.is_true(adapter.filter_dir("src", "", ""))
    assert.is_true(adapter.filter_dir("tests", "", ""))
  end)
end)

