---
name: Test

on:
  push:
    branches: [master]
  pull_request: ~
  workflow_dispatch:

jobs:
  tests:
    name: unit test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-15, windows-2022]
        rev: [v0.10.0]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Setup
        run: |
          nvim --version
          make setup
      # TODO: lib.treesitter.parse_positions builds the tree differently for Windows vs Unix.
      - name: Run unit tests
        if: runner.os == 'Linux'
        run: |
          make unit
      - name: Run integration tests
        run: |
          pip install cmake==3.21 ninja
          make integration
        env:
          CMAKE_GENERATOR: Ninja
      - name: Print logs if failure
        if: ${{ failure() }}
        run: |
          cat .sandbox/state/nvim/neotest.log
          cat .sandbox/state/nvim/nio.log
