---
name: neotest-ctest CI
on:
  push:
    branches:
      - master
  pull_request: ~
jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly, v0.9.1, v0.10.0]
        include:
          - os: ubuntu-22.04
            rev: v0.9.1
          - os: ubuntu-22.04
            rev: v0.10.0
          - os: ubuntu-22.04
            rev: nightly
    steps:
      - uses: actions/checkout@v4
      - name: Prepare dependencies
        run: |
          mkdir -p _neovim
          curl -sL "https://github.com/neovim/neovim/releases/download/${{ matrix.rev }}/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          export PLUGINS_PATH=~/.local/share/nvim/site/pack/vendor/start
          mkdir -p $PLUGINS_PATH
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ${PLUGINS_PATH}/plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ${PLUGINS_PATH}/nvim-treesitter
          git clone --depth 1 https://github.com/nvim-neotest/nvim-nio ${PLUGINS_PATH}/nvim-nio
          git clone --depth 1 https://github.com/nvim-neotest/neotest ${PLUGINS_PATH}/neotest
          ln -s ${PLUGINS_PATH} ~/.local/share/nvim/lazy
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --headless -c 'TSInstallSync lua cpp | quit'
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          nvim --headless -c "PlenaryBustedDirectory tests/unit {minimal_init='tests/unit/minimal_init.lua',timeout=5000}"
